services:

  postgres:
    image: postgres:18.3-trixie
    container_name: madfinancial-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: ${PDB_USER}
      POSTGRES_PASSWORD: ${PDB_PASSWORD}
      POSTGRES_DB: ${PDB_DATABASE}

    ports:
      - "5433:5432"

    volumes:
      - ./madfinancial_database:/var/lib/postgresql
      - ./madfinancial_database/initdb:/docker-entrypoint-initdb.d

    networks:
      - madfinancial-network


  api:
    build:
        context: ./madfinancial_api

    container_name: madfinancial_api

    restart: unless-stopped

    ports:
      - "4000:4000"

    env_file:
      - .env

    depends_on:
      - postgres

    networks:
      - madfinancial-network


networks:
  madfinancial-network:
    driver: bridge
