### Users Login
POST http://localhost:4000/api/v1/users/login
Content-Type: application/json

{
    "email": "rbr1994@hotmail.com",
    "password": "renato"
}

### users create
POST http://localhost:4000/api/v1/users
Content-Type: application/json

{
    "user_id":1,
    "first_name": "Renato",
    "last_name": "bartra Reategui",
    "dni": "71721506",
    "email": "rbr1994@hotmail.com",
    "password": "renato",
    "active": true,
    "image":""
}

### Users Update
PUT http://localhost:4000/api/v1/users/2
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwic29uIjoiUmVuYXRvIGJhcnRyYSBSZWF0ZWd1aSIsImVtYSI6InJicjE5OTRAaG90bWFpbC5jb20iLCJ0b3UiOlsidXNlciJdLCJpYXQiOjE3NzM0Mzk1MjEsImV4cCI6MTc3MzQ1MDMyMX0.R4gpE7zRQuY4gzLM2WLUyf-VsHcnpAQnRYCI20RsDdU

{
    "user_id":2,
    "first_name": "Renato",
    "last_name": "Bartra Reategui",
    "dni": "71721506",
    "email": "rbr1994@hotmail.com",
    "password": "renato",
    "active": true,
    "image":""
}

### DELETE user
DELETE http://localhost:4000/api/v1/users/2
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwic29uIjoiUmVuYXRvIEJhcnRyYSBSZWF0ZWd1aWlpaSIsImVtYSI6InJicjE5OTRAaG90bWFpbC5jb20iLCJ0b3UiOlsidXNlciJdLCJpYXQiOjE3NzIxMjUyNTQsImV4cCI6MTc3MjEzNjA1NH0.CJvBglrv4Ly-CzRWbiUiX5EgCzOx4e008OiWB8I7FTY


### Get all users
GET http://localhost:4000/api/v1/users/
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwic29uIjoiUmVuYXRvIEJhcnRyYSBSZWF0ZWd1aSIsImVtYSI6InJicjE5OTRAaG90bWFpbC5jb20iLCJ0b3UiOlsidXNlciJdLCJpYXQiOjE3NzIwNjA2NTMsImV4cCI6MTc3MjA3MTQ1M30.3_geS4OdD_OkYZr0Tv4ityCiKQ6ed_4-wPk_6gQadig

### forgot password

POST http://localhost:4000/api/v1/forgot-password
Content-Type: application/json

{
    "email": "rbr1994@hotmail.com"
}


### Get all tags
GET http://localhost:4000/api/v1/tags/
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwic29uIjoiUmVuYXRvIEJhcnRyYSBSZWF0ZWd1aSIsImVtYSI6InJicjE5OTRAaG90bWFpbC5jb20iLCJ0b3UiOlsidXNlciJdLCJpYXQiOjE3NzM2ODczMDUsImV4cCI6MTc3MzY5ODEwNX0.aQP_N5SVza6MSh8cNZHUSNw1QNbIWnvsfLldVFPki5A

{
    "user_id": 2
}

### create tags
POST http://localhost:4000/api/v1/tags/
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwic29uIjoiUmVuYXRvIEJhcnRyYSBSZWF0ZWd1aSIsImVtYSI6InJicjE5OTRAaG90bWFpbC5jb20iLCJ0b3UiOlsidXNlciJdLCJpYXQiOjE3NzM2ODczMDUsImV4cCI6MTc3MzY5ODEwNX0.aQP_N5SVza6MSh8cNZHUSNw1QNbIWnvsfLldVFPki5A

{
    "user_id": 2,
    "tag_id": 1,
    "description": "Carimi"
}


### Get all categories
GET http://localhost:4000/api/v1/categories/
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwic29uIjoiUmVuYXRvIEJhcnRyYSBSZWF0ZWd1aSIsImVtYSI6InJicjE5OTRAaG90bWFpbC5jb20iLCJ0b3UiOlsidXNlciJdLCJpYXQiOjE3NzM3OTA2OTgsImV4cCI6MTc3MzgwMTQ5OH0.dVHljS94VLeCyOO3CSl7-16TIlh6qT5w0z17nVmsABE

{
    "user_id": 2
}

### create categories
POST http://localhost:4000/api/v1/categories/
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwic29uIjoiUmVuYXRvIEJhcnRyYSBSZWF0ZWd1aSIsImVtYSI6InJicjE5OTRAaG90bWFpbC5jb20iLCJ0b3UiOlsidXNlciJdLCJpYXQiOjE3NzM3OTA2OTgsImV4cCI6MTc3MzgwMTQ5OH0.dVHljS94VLeCyOO3CSl7-16TIlh6qT5w0z17nVmsABE

{
    "user_id": 2,
    "category_id": 1,
    "category_type": true,
    "description": "Transferencia"
}



### Get all accounts
GET http://localhost:4000/api/v1/accounts/
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwic29uIjoiUmVuYXRvIEJhcnRyYSBSZWF0ZWd1aSIsImVtYSI6InJicjE5OTRAaG90bWFpbC5jb20iLCJ0b3UiOlsidXNlciJdLCJpYXQiOjE3NzM5NjY4MTAsImV4cCI6MTc3Mzk3NzYxMH0.RwdlnJM-Fx4k-FsGS_ExEVHb4HWjzUWGOvxdyIo_uXI

{
    "user_id": 2
}

### create account
POST http://localhost:4000/api/v1/accounts/
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwic29uIjoiUmVuYXRvIEJhcnRyYSBSZWF0ZWd1aSIsImVtYSI6InJicjE5OTRAaG90bWFpbC5jb20iLCJ0b3UiOlsidXNlciJdLCJpYXQiOjE3NzM5NjY4MTAsImV4cCI6MTc3Mzk3NzYxMH0.RwdlnJM-Fx4k-FsGS_ExEVHb4HWjzUWGOvxdyIo_uXI

{
    "user_id": 2,
    "account_id": 1,
    "description": "Efectivo"
}


### create movement
POST http://localhost:4000/api/v1/movements/
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwic29uIjoiUmVuYXRvIEJhcnRyYSBSZWF0ZWd1aSIsImVtYSI6InJicjE5OTRAaG90bWFpbC5jb20iLCJ0b3UiOlsidXNlciJdLCJpYXQiOjE3NzQ5MDk3OTAsImV4cCI6MTc3NDkyMDU5MH0.TEjWDqVtDKOZzmtVlNrZXADg7L0uEmHqhFoArhJIl6k

{
    "movement_id":1,
    "user_id": 2,
    "title":"Compras semana",
    "description": "Compras semana en Plaza Vea",
    "amount":100,
    "accounting_date": "2026-03-31",
    "type":{
        "type_id":2,
        "description":"Gasto"
    },
    "category":{
        "category_id":3,
        "category_type": true,
        "description":"Supermercado"
    },
    "account":{
        "account_id":1,
        "description":"Sueldo"
    },
    "tags":[],
    "submovements": [
        {
            "submovement_id": 1,
            "subcategory": {
                "category_id":13,
                "category_type": true,
                "description":"Limpieza"
            },
            "amount": 40,
            "description": "Shampoo Carimi",
            "tags": [
                {"tag_id":2,"description":"Carimi"}
            ]
        },
        {
            "submovement_id": 1,
            "subcategory": {
                "category_id":1,
                "category_type": true,
                "description":"Comida"
            },
            "amount": 60,
            "description": "Comida para casa",
            "tags": []
        }
    ]
}

### get movements by date
GET http://localhost:4000/api/v1/movements/
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwic29uIjoiUmVuYXRvIEJhcnRyYSBSZWF0ZWd1aSIsImVtYSI6InJicjE5OTRAaG90bWFpbC5jb20iLCJ0b3UiOlsidXNlciJdLCJpYXQiOjE3NzQ5MDk3OTAsImV4cCI6MTc3NDkyMDU5MH0.TEjWDqVtDKOZzmtVlNrZXADg7L0uEmHqhFoArhJIl6k

{"accounting_date": "2026-03-31"}

### Delete movements
DELETE http://localhost:4000/api/v1/movements/18
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwic29uIjoiUmVuYXRvIEJhcnRyYSBSZWF0ZWd1aSIsImVtYSI6InJicjE5OTRAaG90bWFpbC5jb20iLCJ0b3UiOlsidXNlciJdLCJpYXQiOjE3NzU0NDM0ODQsImV4cCI6MTc3NTQ1NDI4NH0.fVgnahu12fZvr-girPXOA0QWa5SxI2eOCtb5RrI6gnw

### Update movement
PUT http://localhost:4000/api/v1/movements/23
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwic29uIjoiUmVuYXRvIEJhcnRyYSBSZWF0ZWd1aSIsImVtYSI6InJicjE5OTRAaG90bWFpbC5jb20iLCJ0b3UiOlsidXNlciJdLCJpYXQiOjE3NzQ5MDk3OTAsImV4cCI6MTc3NDkyMDU5MH0.TEjWDqVtDKOZzmtVlNrZXADg7L0uEmHqhFoArhJIl6k

{
    "movement_id":1,
    "user_id": 2,
    "title":"Compras semana",
    "description": "Compras semana en Plaza Vea",
    "amount":100,
    "accounting_date": "2026-03-31",
    "type":{
        "type_id":2,
        "description":"Gasto"
    },
    "category":{
        "category_id":3,
        "category_type": true,
        "description":"Supermercado"
    },
    "account":{
        "account_id":1,
        "description":"Sueldo"
    },
    "tags":[],
    "submovements": [
        {
            "submovement_id": 1,
            "subcategory": {
                "category_id":13,
                "category_type": true,
                "description":"Limpieza"
            },
            "amount": 40,
            "description": "Shampoo Carimi",
            "tags": [
                {"tag_id":2,"description":"Carimi"}
            ]
        },
        {
            "submovement_id": 1,
            "subcategory": {
                "category_id":1,
                "category_type": true,
                "description":"Comida"
            },
            "amount": 60,
            "description": "Comida para casa",
            "tags": []
        }
    ]
}